# -*- coding: utf-8 -*-
"""category_breakdown.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-LGREoL5UKhkL7prDuZ0I4lg5zW419Ms
"""

import matplotlib.pyplot as plt
# Dataset
categories = ["Food", "Travel", "Shopping"]
expenses = [500, 300, 200]
explode = [0.1, 0, 0]
plt.figure(figsize=(7, 7))

plt.pie(
    expenses,
    labels=categories,
    autopct='%1.1f%%',
    explode=explode,
    shadow=True,
    startangle=90
)
plt.title("Expense Category Breakdown")
plt.savefig("pie_chart.png")
plt.show()
highest_expense = max(expenses)
highest_category = categories[expenses.index(highest_expense)]

print("Highest Expense Category:", highest_category)
print("Amount:", highest_expense)