# -*- coding: utf-8 -*-
"""student_performance_dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tx-Q6ADQwujIgi9zjiBh6JbCBG8UDkUT
"""

import matplotlib.pyplot as plt
import numpy as np

# Dataset
students = ["AMIT", "RIYA", "JOHN"]
marks = [85, 92, 78]
math_marks = [85, 92, 78]
science_marks = [80, 88, 82]
plt.figure(figsize=(8, 5))
bars = plt.bar(students, marks)

for bar in bars:
    height = bar.get_height()
    plt.text(
        bar.get_x() + bar.get_width()/2,
        height + 1,
        f"{height}",
        ha='center'
    )
plt.title("Student Performance Dashboard")
plt.xlabel("Students")
plt.ylabel("Marks")
plt.savefig("student_performance_chart.png")
plt.show()

x = np.arange(len(students))
width = 0.35

plt.figure(figsize=(8, 5))

plt.bar(x - width/2, math_marks, width, label="Math")
plt.bar(x + width/2, science_marks, width, label="Science")
plt.xticks(x, students)
plt.title(" Subject-wise Student Comparison")
plt.xlabel("Students")
plt.ylabel("Marks")
plt.legend()
plt.grid(axis='y')
plt.show()

print(" Student dashboard charts generated successfully.")