# -*- coding: utf-8 -*-
"""sales_customers_insights.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mh94Pzg99EA2omO2E29hzQw8AECdM73a
"""

# Day 22 - Sales & Customer Insights Dashboard
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("sales_customer_dataset.csv")

print("=" * 60)
print("SALES & CUSTOMER INSIGHTS DASHBOARD")
print("=" * 60)

print("\nOriginal Dataset Shape:", df.shape)
print("\nFirst 5 Rows:")
print(df.head())

print("\n" + "-" * 60)
print("DATA CLEANING")
print("-" * 60)

df["Date"] = pd.to_datetime(df["Date"], errors="coerce")

print("\nMissing Values Before Cleaning:")
print(df.isnull().sum())

duplicate_count = df.duplicated().sum()
df = df.drop_duplicates()
df["Customer"] = df["Customer"].fillna(df["Customer"].mode()[0])
df["Category"] = df["Category"].fillna(df["Category"].mode()[0])
df["Revenue"] = df["Revenue"].fillna(df["Revenue"].median())
if df["Date"].isnull().any():
    df["Date"] = df["Date"].fillna(df["Date"].mode()[0])

print("\nDuplicate Rows Removed:", duplicate_count)

print("\nMissing Values After Cleaning:")
print(df.isnull().sum())

print("\nCleaned Dataset Shape:", df.shape)

total_sales = df["Revenue"].sum()
average_revenue = df["Revenue"].mean()

print("\n" + "-" * 60)
print("SALES SUMMARY")
print("-" * 60)

print(f"Total Sales / Revenue: ₹{total_sales:,.2f}")
print(f"Average Revenue per Transaction: ₹{average_revenue:,.2f}")

top_customers = (
    df.groupby("Customer")["Revenue"]
    .sum()
    .sort_values(ascending=False)
    .head(5)
)

print("\n" + "-" * 60)
print("TOP 5 CUSTOMERS")
print("-" * 60)

print(top_customers)


sales_trend = (
    df.groupby("Date")["Revenue"]
    .sum()
    .sort_index()
)


top_products = (
    df.groupby("Product")["Revenue"]
    .sum()
    .sort_values(ascending=False)
)

print("\n" + "-" * 60)
print("TOP PRODUCTS")
print("-" * 60)

print(top_products)

category_sales = (
    df.groupby("Category")["Revenue"]
    .sum()
    .sort_values(ascending=False)
)

print("\n" + "-" * 60)
print("CATEGORY DISTRIBUTION")
print("-" * 60)

print(category_sales)


plt.figure(figsize=(12, 6))

plt.plot(
    sales_trend.index,
    sales_trend.values,
    marker="o",
    linewidth=2
)

plt.title("Sales Trend Over Time")
plt.xlabel("Date")
plt.ylabel("Revenue (₹)")
plt.xticks(rotation=45)
plt.grid(True, alpha=0.3)
plt.tight_layout()

plt.savefig("sales_trend.png", dpi=300)
plt.show()


plt.figure(figsize=(10, 6))

top_products.head(5).sort_values().plot(
    kind="barh"
)

plt.title("Top 5 Products by Revenue")
plt.xlabel("Revenue (₹)")
plt.ylabel("Product")
plt.tight_layout()

plt.savefig("top_products.png", dpi=300)
plt.show()


plt.figure(figsize=(8, 8))

plt.pie(
    category_sales,
    labels=category_sales.index,
    autopct="%1.1f%%",
    startangle=90
)

plt.title("Category-wise Revenue Distribution")
plt.tight_layout()

plt.savefig("category_distribution.png", dpi=300)
plt.show()


highest_customer = top_customers.index[0]
highest_customer_sales = top_customers.iloc[0]

best_product = top_products.index[0]
best_product_sales = top_products.iloc[0]

best_category = category_sales.index[0]
best_category_sales = category_sales.iloc[0]

best_sales_date = sales_trend.idxmax()
best_sales_day_revenue = sales_trend.max()

print("\n" + "=" * 60)
print("5 BUSINESS INSIGHTS")
print("=" * 60)

print(
    f"1. {highest_customer} is the highest-value customer, "
    f"generating ₹{highest_customer_sales:,.2f} in revenue."
)

print(
    f"2. {best_product} is the top revenue-generating product, "
    f"contributing ₹{best_product_sales:,.2f}."
)

print(
    f"3. {best_category} is the leading product category, "
    f"with revenue of ₹{best_category_sales:,.2f}."
)

print(
    f"4. The highest single-day revenue was recorded on "
    f"{best_sales_date.strftime('%d-%m-%Y')}, "
    f"with ₹{best_sales_day_revenue:,.2f} in sales."
)

print(
    f"5. The average revenue per transaction is "
    f"₹{average_revenue:,.2f}, providing a useful indicator "
    f"of average transaction value."
)


print("\n" + "=" * 60)
print("PROJECT COMPLETED SUCCESSFULLY")
print("=" * 60)

print(f"Total Transactions: {len(df)}")
print(f"Total Revenue: ₹{total_sales:,.2f}")
print(f"Average Revenue: ₹{average_revenue:,.2f}")
print(f"Top Customer: {highest_customer}")
print(f"Top Product: {best_product}")
print(f"Top Category: {best_category}")

print("\nCharts saved:")
print("- sales_trend.png")
print("- top_products.png")
print("- category_distribution.png")