# -*- coding: utf-8 -*-
"""fraud_detection_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RmhiAjAvtkPAxfjbQ55pyoyAeYO4D8MV
"""

from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt

BASE_DIR = Path('/content/')
df = pd.read_csv(BASE_DIR / "transactions_dataset.csv")
df["Transaction_Date"] = pd.to_datetime(df["Transaction_Date"])

HIGH_VALUE_THRESHOLD = 50000
FREQUENT_TRANSACTION_THRESHOLD = 10

duplicates = df[df.duplicated(keep=False)].copy()
high_value_transactions = df[df["Amount"] > HIGH_VALUE_THRESHOLD].copy()

account_frequency = df.groupby("Account_ID").size().reset_index(name="Transaction_Count")
suspicious_accounts = account_frequency[
    account_frequency["Transaction_Count"] >= FREQUENT_TRANSACTION_THRESHOLD
]["Account_ID"]

df["Risk_Score"] = 0
df.loc[df["Amount"] > HIGH_VALUE_THRESHOLD, "Risk_Score"] += 40
df.loc[df["Amount"] > 100000, "Risk_Score"] += 20
df.loc[df["Account_ID"].isin(suspicious_accounts), "Risk_Score"] += 25
df.loc[df.duplicated(keep=False), "Risk_Score"] += 35
df.loc[df["Status"] == "Failed", "Risk_Score"] += 10
df["Risk_Score"] = df["Risk_Score"].clip(upper=100)

df["Risk_Level"] = pd.cut(
    df["Risk_Score"], [-1,24,49,74,100],
    labels=["Low","Medium","High","Critical"]
)

suspicious_transactions = df[
    (df["Risk_Score"] >= 50) | (df["Amount"] > HIGH_VALUE_THRESHOLD) | df.duplicated(keep=False)
].copy()
suspicious_transactions.to_csv(BASE_DIR / "suspicious_transactions.csv", index=False)

print("Total Transactions:", len(df))
print("Duplicate Records:", len(duplicates))
print("High-Value Transactions:", len(high_value_transactions))
print("Suspicious Accounts:", len(suspicious_accounts))
print("\nTop 10 Highest Transactions:")
print(df.nlargest(10, "Amount")[["Transaction_ID","Account_ID","Amount","Transaction_Category","Risk_Score"]].to_string(index=False))

category_counts = df["Transaction_Category"].value_counts()
plt.figure(figsize=(10,6))
plt.bar(category_counts.index, category_counts.values)
plt.title("Transaction Category Chart")
plt.xlabel("Category")
plt.ylabel("Number of Transactions")
plt.xticks(rotation=30, ha="right")
plt.tight_layout()
plt.savefig(BASE_DIR / "transaction_category_chart.png", dpi=300)
plt.show()

df["Date"] = df["Transaction_Date"].dt.date
daily = df.groupby("Date").size()
plt.figure(figsize=(12,6))
plt.plot(daily.index, daily.values, marker="o", markersize=3)
plt.title("Daily Transaction Trend")
plt.xlabel("Date")
plt.ylabel("Transactions")
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig(BASE_DIR / "daily_transaction_trend.png", dpi=300)
plt.show()

# --------------------------------------------------
# TOP 10 HIGHEST TRANSACTIONS
# --------------------------------------------------

top_10_transactions = df.nlargest(10, "Amount")

plt.figure(figsize=(12, 6))

plt.barh(
    top_10_transactions["Transaction_ID"].astype(str),
    top_10_transactions["Amount"]
)

plt.title("Top 10 Highest Transactions")
plt.xlabel("Transaction Amount")
plt.ylabel("Transaction ID")

plt.gca().invert_yaxis()

plt.tight_layout()

plt.savefig("top_10_transactions.png")

plt.show()