# -*- coding: utf-8 -*-
"""intermediate_function.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x2i-LNApFC3K9VBYLQGblb8976ASfJGN
"""

# Day 21 - Functions: Intermediate
# Task 1: Check whether a number is prime

def is_prime(number):
    if number <= 1:
        return False

    for i in range(2, int(number ** 0.5) + 1):
        if number % i == 0:
            return False

    return True
# Task 2: Find largest number using *args

def find_largest(*args):
    if not args:
        return None

    largest = args[0]

    for number in args:
        if number > largest:
            largest = number

    return largest
# Task 3: Student information using **kwargs

def student_information(**kwargs):
    print("\nStudent Information")

    for key, value in kwargs.items():
        print(f"{key}: {value}")
# Task 4: Calculate statistics
def calculate_statistics(numbers):
    if not numbers:
        return None

    maximum = max(numbers)
    minimum = min(numbers)
    total = sum(numbers)
    average = total / len(numbers)

    return maximum, minimum, average, total

# Testing

if __name__ == "__main__":

    # Task 1
    number = 17

    if is_prime(number):
        print(f"{number} is a prime number.")
    else:
        print(f"{number} is not a prime number.")

    # Task 2
    numbers = [12, 45, 7, 89, 23, 56]
    print("\nNumbers:", numbers)
    print("Largest number:", find_largest(*numbers))

    # Task 3
    student_information(
        name="Shreya",
        course="B.Tech CSE",
        specialization="AI & ML",
        semester=6
    )

    # Task 4
    data = [10, 20, 30, 40, 50]

    maximum, minimum, average, total = calculate_statistics(data)

    print("\nStatistics")
    print("Numbers:", data)
    print("Maximum:", maximum)
    print("Minimum:", minimum)
    print("Average:", average)
    print("Sum:", total)