# -*- coding: utf-8 -*-
"""customer_segmentation_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H6YHL9NTJUfmDmGNnhOMCLoGQOdC6MX1
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
data = {
    "Customer_ID": [101, 102, 103, 104, 105, 106],
    "Age": [22, 35, 28, 45, 32, 26],
    "Spending": [2000, 7000, 3000, 12000, 5000, 1500],
    "Visits": [5, 12, 6, 20, 10, 3]
}

df = pd.DataFrame(data)
def customer_segment(spending):
    if spending >= 8000:
        return "High"
    elif spending >= 4000:
        return "Medium"
    else:
        return "Low"

df["Segment"] = df["Spending"].apply(customer_segment)
print("\n Customer Segments:\n")
print(df)

high_value = df[df["Segment"] == "High"]
print("\n High Value Customers:\n")
print(high_value)

low_engagement = df[df["Visits"] < 5]
print("\n Low Engagement Customers:\n")
print(low_engagement)

sns.set_style("whitegrid")



plt.figure(figsize=(5, 3))
sns.histplot(
    df["Spending"],
    bins=5,
    kde=True
)

plt.title(" Customer Spending Distribution")
plt.xlabel("Spending")
plt.ylabel("Frequency")
plt.tight_layout()
plt.savefig("spending_distribution.png")
plt.show()
plt.figure(figsize=(5, 3))
sns.countplot(
    x="Segment",
    data=df
)
plt.title(" Customer Segments")
plt.xlabel("Segment")
plt.ylabel("Count")
plt.tight_layout()
plt.savefig("customer_segments.png")
plt.show()


print("\n Business Insights:")

high_count = len(df[df["Segment"] == "High"])
medium_count = len(df[df["Segment"] == "Medium"])
low_count = len(df[df["Segment"] == "Low"])

print(f" High Value Customers: {high_count}")
print(f" Medium Value Customers: {medium_count}")
print(f" Low Value Customers: {low_count}")
print("\n Suggested Strategies:")
print("- Offer premium rewards to high-value customers")
print("- Improve engagement campaigns for low-engagement users")
print("- Provide personalized recommendations")