# -*- coding: utf-8 -*-
"""Salary_insights.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y2w3KT7AD__hBN0cN_P1VeFWoSKVNe1N
"""

employees = []
with open("employee_salary.csv", "r") as file:
    lines = file.readlines()
    for line in lines[1:]:
        data = line.strip().split(",")

        employee = {
            "NAME": data[0],
            "DEPT": data[1],
            "SALARY": int(data[2])
        }
        employees.append(employee)
print(" Employee Records:\n")

for emp in employees:
    print(emp)
department_data = {}

for emp in employees:
    dept = emp["DEPT"]
    if dept not in department_data:
        department_data[dept] = []
    department_data[dept].append(emp)
print("\n Average Salary Per Department:")

department_avg = {}

for dept, emp_list in department_data.items():
    total_salary = sum(emp["SALARY"] for emp in emp_list)
    avg_salary = total_salary / len(emp_list)
    department_avg[dept] = avg_salary
    print(f"{dept}: {avg_salary:.2f}")
print("\n Highest Paid Employee Per Department:")

for dept, emp_list in department_data.items():
    highest_paid = max(emp_list, key=lambda x: x["SALARY"])

    print(f"{dept}: {highest_paid['NAME']} ({highest_paid['SALARY']})")
print("\n Employee Count Per Department:")

for dept, emp_list in department_data.items():
    print(f"{dept}: {len(emp_list)}")
print("\n Departments Sorted by Average Salary:")

sorted_departments = sorted(
    department_avg.items(),
    key=lambda x: x[1],
    reverse=True
)

for dept, avg_salary in sorted_departments:
    print(f"{dept}: {avg_salary:.2f}")