# -*- coding: utf-8 -*-
"""Data_filtering_tool.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j7H6WBOu22_y35Js3CVq0xbC-AJs1neN
"""

employees = []
with open("employee_data.csv", "r") as file:
    lines = file.readlines()
    for line in lines[1:]:
        data = line.strip().split(",")

        employee = {
            "NAME": data[0],
            "AGE": int(data[1]),
            "DEPT": data[2],
            "SALARY": int(data[3])
        }

        employees.append(employee)
filtered_employees = []

for emp in employees:
    if emp["SALARY"] > 50000 and emp["AGE"] < 30:
        filtered_employees.append(emp)
print("Filtered Employees:\n")

for emp in filtered_employees:
    print(emp)
with open("filtered_data.csv", "w") as file:
    file.write("NAME,AGE,DEPT,SALARY\n")

    for emp in filtered_employees:
        row = f"{emp['NAME']},{emp['AGE']},{emp['DEPT']},{emp['SALARY']}\n"
        file.write(row)

print("\n Filtered data saved to filtered_data.csv")