# -*- coding: utf-8 -*-
"""csv_reader.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uIpXmCU_e3yBWhp_8aE40YQempPHJOQJ
"""

students = []

# Open and read CSV file
with open("student_data.csv", "r") as file:
    lines = file.readlines()

    # Skip header row
    for line in lines[1:]:
        data = line.strip().split(",")

        # Handle missing values
        if len(data) != 3 or "" in data:
            continue

        name = data[0]
        age = int(data[1])
        marks = int(data[2])

        student = {
            "NAME": name,
            "AGE": age,
            "MARKS": marks
        }

        students.append(student)

# Display structured data
print("Student Records:\n")

for student in students:
    print(student)

# Calculate average marks
total_marks = sum(student["MARKS"] for student in students)
average_marks = total_marks / len(students)

print(f"\n Average Marks: {average_marks:.2f}")