# -*- coding: utf-8 -*-
"""phonebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q4YVCbcor4jhjN_qWuIZpXja07iioR2a
"""

# Dictionary-Based Phonebook

phonebook = {
    "AMIT": "9876543210",
    "RIYA": "9123456780"
}


# Add Contact
def add_contact():
    name = input("Enter name: ").upper()

    if name in phonebook:
        print("Contact already exists!")
        return

    number = input("Enter phone number: ")
    phonebook[name] = number
    print("Contact added successfully.")


# Search Contact
def search_contact():
    search = input("Enter name to search: ").upper()

    found = False

    for name, number in phonebook.items():
        if search in name:   # Partial search bonus
            print(f" {name} : {number}")
            found = True

    if not found:
        print("Contact not found.")


# Delete Contact
def delete_contact():
    name = input("Enter contact name to delete: ").upper()

    if name in phonebook:
        del phonebook[name]
        print("Contact deleted successfully.")
    else:
        print("Contact not found.")


# Display Contacts
def display_contacts():
    if not phonebook:
        print("Phonebook is empty.")
    else:
        print("\nPhonebook Contacts:")
        for name, number in phonebook.items():
            print(f"{name} : {number}")


# Main Menu
while True:
    print("\n===== PHONEBOOK MENU =====")
    print("1. Add Contact")
    print("2. Search Contact")
    print("3. Delete Contact")
    print("4. Display Contacts")
    print("5. Exit")

    choice = input("Enter your choice: ")

    if choice == "1":
        add_contact()

    elif choice == "2":
        search_contact()

    elif choice == "3":
        delete_contact()

    elif choice == "4":
        display_contacts()

    elif choice == "5":
        print("Exiting Phonebook...")
        break

    else:
        print("Invalid choice. Try again.")