# -*- coding: utf-8 -*-
"""distribution_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jtzaRaLNgltZPcOlw4yHtgibPabLlOoT
"""

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
marks = [55, 60, 65, 70, 72, 75, 78, 80, 82, 85,
         87, 90, 92, 95, 97, 100]
sns.set_style("whitegrid")
plt.figure(figsize=(8, 5))

sns.histplot(
    marks,
    bins=8,
    kde=True
)
plt.title("Distribution Analysis of Student Marks")
plt.xlabel("Marks")
plt.ylabel("Frequency")
plt.savefig("distribution_plot.png")
plt.show()
mean_value = np.mean(marks)
median_value = np.median(marks)

print(" Mean   :", round(mean_value, 2))
print("Median :", round(median_value, 2))
if mean_value > median_value:
    print("Distribution is Positively Skewed")
elif mean_value < median_value:
    print("Distribution is Negatively Skewed")
else:
    print("Distribution is Approximately Symmetric")