# -*- coding: utf-8 -*-
"""Sales_Data_Analyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KVSbmu9Q0LqHQT7uuvycNTnEAV8m57hN
"""

sales = []
with open("sales_data.csv", "r") as file:
    lines = file.readlines()

    for line in lines[1:]:
        # Changed the split delimiter from "," to "\t"
        data = line.strip().split("\t")

        product = data[0]
        quantity = int(data[1])
        price = int(data[2])
        total = quantity * price

        record = {
            "PRODUCT": product,
            "QUANTITY": quantity,
            "PRICE": price,
            "TOTAL": total
        }

        sales.append(record)
print("Sales Records:\n")

for item in sales:
    print(item)

total_revenue = sum(item["TOTAL"] for item in sales)

print(f"\n Total Revenue: {total_revenue}")

product_sales = {}

for item in sales:
    product = item["PRODUCT"]

    if product not in product_sales:
        product_sales[product] = 0

    product_sales[product] += item["TOTAL"]

print("\n Total Sales Per Product:")

for product, revenue in product_sales.items():
    print(f"{product}: {revenue}")

top_product = max(product_sales, key=product_sales.get)

print(f"\n Top-Selling Product: {top_product}")

sorted_sales = sorted(
    product_sales.items(),
    key=lambda x: x[1],
    reverse=True
)

print("\n Products Sorted by Revenue:")

for product, revenue in sorted_sales:
    print(f"{product}: {revenue}")