# -*- coding: utf-8 -*-
"""score_analyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_eqtwaiQgiDMy0gJ5kKH65Jpzc3hTIEn
"""

marks = [78, 85, 90, 67, 85, 92, 78]

def analyze_scores(marks):
    avg = sum(marks) / len(marks)
    highest = max(marks)
    lowest = min(marks)

    # Count above average
    above_avg = sum(1 for m in marks if m > avg)

    # Grade distribution
    grades = {"A": 0, "B": 0, "C": 0, "Fail": 0}

    for m in marks:
        if m >= 90:
            grades["A"] += 1
        elif m >= 75:
            grades["B"] += 1
        elif m >= 50:
            grades["C"] += 1
        else:
            grades["Fail"] += 1

    return avg, highest, lowest, above_avg, grades


avg, highest, lowest, above_avg, grades = analyze_scores(marks)

print("Average:", round(avg,2))
print("Highest:", highest)
print("Lowest:", lowest)
print("Students above average:", above_avg)
print("Grade Distribution:", grades)