# -*- coding: utf-8 -*-
"""mini_eda_dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pe_zUb8g3KGILb53GRvjUpp5xTCACPMS
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Sample dataset
data = {
    "Day": ["Mon", "Tue", "Wed", "Thu", "Fri"],
    "Sales": [200, 250, 300, 280, 350],
    "Customers": [20, 25, 27, 24, 35]
}
df = pd.DataFrame(data)
sns.set_style("whitegrid")
fig, axes = plt.subplots(1, 3, figsize=(18, 5))
axes[0].plot(df["Day"], df["Sales"], marker='o', linewidth=3)
axes[0].set_title(" Sales Trend")
axes[0].set_xlabel("Day")
axes[0].set_ylabel("Sales")
sns.barplot(
    x="Day",
    y="Customers",
    data=df,
    ax=axes[1]
)
axes[1].set_title(" Customer Comparison")
axes[1].set_xlabel("Day")
axes[1].set_ylabel("Customers")

sns.histplot(
    df["Sales"],
    kde=True,
    bins=5,
    ax=axes[2]
)
axes[2].set_title(" Sales Distribution")
axes[2].set_xlabel("Sales")
plt.tight_layout()
plt.savefig("mini_eda_dashboard.png")
plt.show()
highest_sales = df["Sales"].max()
best_day = df[df["Sales"] == highest_sales]["Day"].values[0]
avg_sales = df["Sales"].mean()
print("\n Insights:")
print(f" Highest Sales: {highest_sales} on {best_day}")
print(f" Average Sales: {avg_sales:.2f}")
q1 = df["Sales"].quantile(0.25)
q3 = df["Sales"].quantile(0.75)
iqr = q3 - q1
lower_bound = q1 - 1.5 * iqr
upper_bound = q3 + 1.5 * iqr
outliers = df[(df["Sales"] < lower_bound) | (df["Sales"] > upper_bound)]
if len(outliers) > 0:
    print(" Outliers Detected:")
    print(outliers)
else:
    print(" No Outliers Detected")