# -*- coding: utf-8 -*-
"""Student_performance_analyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D5TszdUJG_HlcJP3HzsGJ6Zu9rC3W-u2
"""

students = []

with open("student_performance.csv", "r") as file:
    lines = file.readlines()
    for line in lines[1:]:
        data = line.strip().split(",")

        name = data[0]
        math = int(data[1])
        science = int(data[2])
        english = int(data[3])
        average = (math + science + english) / 3
        if average >= 85:
            grade = "A"
        elif average >= 70:
            grade = "B"
        else:
            grade = "C"
        student = {
            "NAME": name,
            "MATH": math,
            "SCIENCE": science,
            "ENGLISH": english,
            "AVERAGE": round(average, 2),
            "GRADE": grade
        }

        students.append(student)

print(" Student Performance Dashboard:\n")

for student in students:
    print(student)
topper = max(students, key=lambda x: x["AVERAGE"])

print(f"\n Topper: {topper['NAME']} ({topper['AVERAGE']})")
class_average = sum(student["AVERAGE"] for student in students) / len(students)

print(f"\n Class Average: {class_average:.2f}")
above_average = 0

for student in students:
    if student["AVERAGE"] > class_average:
        above_average += 1

print(f"\n Students Above Average: {above_average}")

math_avg = sum(student["MATH"] for student in students) / len(students)
science_avg = sum(student["SCIENCE"] for student in students) / len(students)
english_avg = sum(student["ENGLISH"] for student in students) / len(students)

print("\n Subject-wise Average:")
print(f"Math: {math_avg:.2f}")
print(f"Science: {science_avg:.2f}")
print(f"English: {english_avg:.2f}")