# -*- coding: utf-8 -*-
"""log_analyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y1tZAUDXR8hedQHYFBWC9UHT0dsdorlF
"""

logs = [
    "ERROR Disk Full",
    "INFO Started",
    "ERROR File Missing",
    "WARNING Memory Low",
    "info User logged in",
    "warning CPU usage high",
    "ERROR Connection Failed"
]


error_count = 0
info_count = 0
warning_count = 0

# Dictionary for frequency tracking
log_frequency = {}


for log in logs:

    log_upper = log.upper()

    if "ERROR" in log_upper:
        error_count += 1
        log_type = "ERROR"

    elif "INFO" in log_upper:
        info_count += 1
        log_type = "INFO"

    elif "WARNING" in log_upper:
        warning_count += 1
        log_type = "WARNING"

    else:
        log_type = "OTHER"

    # Frequency tracking
    if log_type in log_frequency:
        log_frequency[log_type] += 1
    else:
        log_frequency[log_type] = 1


# Find most frequent log type
most_frequent = max(log_frequency, key=log_frequency.get)


# Output
print("Log Analysis Report")
print("-" * 30)

print(f" ERROR Logs   : {error_count}")
print(f" INFO Logs    : {info_count}")
print(f" WARNING Logs : {warning_count}")

print("\n Log Frequency:")
for key, value in log_frequency.items():
    print(f"{key} : {value}")

print(f"\n Most Frequent Log Type: {most_frequent}")