# -*- coding: utf-8 -*-
"""social_media_trend_analyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vKDfGKSpHDRm1RRVjQXu5KYKh8IqqFLy
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re

from google.colab import files

uploaded = files.upload()

file_name = list(uploaded.keys())[0]

df = pd.read_csv(file_name)

print("Dataset loaded successfully!")
print("Shape:", df.shape)

df.head()

# Check dataset information
print(df.info())

# Check missing values
print("\nMissing Values:")
print(df.isnull().sum())

# Remove duplicate posts
df = df.drop_duplicates(subset="Post_ID")

# Convert engagement columns to numeric
engagement_columns = ["Likes", "Comments", "Shares"]

for col in engagement_columns:
    df[col] = pd.to_numeric(df[col], errors="coerce").fillna(0)

# Convert Date column
df["Date"] = pd.to_datetime(df["Date"], errors="coerce")

# Create Total Engagement
df["Total_Engagement"] = (
    df["Likes"] +
    df["Comments"] +
    df["Shares"]
)

# Extract posting hour
df["Posting_Hour"] = pd.to_datetime(
    df["Time"],
    format="%H:%M:%S",
    errors="coerce"
).dt.hour

print("Data cleaned successfully!")

df.head()

# Extract all hashtags
all_hashtags = []

for hashtags in df["Hashtags"].dropna():
    tags = re.findall(r"#\w+", str(hashtags))
    all_hashtags.extend([tag.lower() for tag in tags])

# Count hashtags
hashtag_counts = (
    pd.Series(all_hashtags)
    .value_counts()
    .reset_index()
)

hashtag_counts.columns = ["Hashtag", "Count"]

top_hashtags = hashtag_counts.head(10)

print("🔥 Top Trending Hashtags")
print(top_hashtags)

plt.figure(figsize=(10, 6))

plt.bar(
    top_hashtags["Hashtag"],
    top_hashtags["Count"]
)

plt.title("Top 10 Trending Hashtags")
plt.xlabel("Hashtag")
plt.ylabel("Number of Posts")

plt.xticks(rotation=45)

plt.tight_layout()

plt.show()

active_users = (
    df["User"]
    .value_counts()
    .reset_index()
)

active_users.columns = ["User", "Posts"]

print("👥 Most Active Users")
print(active_users.head(10))

total_likes = df["Likes"].sum()
total_comments = df["Comments"].sum()
total_shares = df["Shares"].sum()
total_engagement = df["Total_Engagement"].sum()

average_engagement = df["Total_Engagement"].mean()

print("📊 ENGAGEMENT ANALYSIS")
print("-" * 35)

print(f"Total Likes: {total_likes:,}")
print(f"Total Comments: {total_comments:,}")
print(f"Total Shares: {total_shares:,}")
print(f"Total Engagement: {total_engagement:,}")
print(f"Average Engagement per Post: {average_engagement:,.2f}")

popular_posting_time = (
    df["Posting_Hour"]
    .value_counts()
    .sort_values(ascending=False)
)

most_popular_hour = popular_posting_time.index[0]

print("🕒 MOST POPULAR POSTING TIME")
print(
    f"{most_popular_hour:02d}:00 - "
    f"{(most_popular_hour + 1) % 24:02d}:00"
)

popular_posting_time.head(10)

daily_engagement = (
    df.groupby("Date")["Total_Engagement"]
    .sum()
    .reset_index()
)

plt.figure(figsize=(12, 6))

plt.plot(
    daily_engagement["Date"],
    daily_engagement["Total_Engagement"],
    marker="o"
)

plt.title("Daily Engagement Trend")
plt.xlabel("Date")
plt.ylabel("Total Engagement")

plt.xticks(rotation=45)

plt.tight_layout()

plt.show()

category_distribution = (
    df["Category"]
    .value_counts()
)

plt.figure(figsize=(8, 8))

plt.pie(
    category_distribution.values,
    labels=category_distribution.index,
    autopct="%1.1f%%",
    startangle=90
)

plt.title("Content Category Distribution")

plt.tight_layout()

plt.show()

positive_words = [
    "love", "loved", "amazing", "fantastic",
    "great", "happy", "excited", "wonderful",
    "excellent", "inspiring", "achievement"
]

negative_words = [
    "disappointing", "frustrating", "poor",
    "problems", "not happy", "improvement",
    "issues"
]


def analyze_sentiment(text):

    text = str(text).lower()

    positive_score = sum(
        word in text
        for word in positive_words
    )

    negative_score = sum(
        word in text
        for word in negative_words
    )

    if positive_score > negative_score:
        return "Positive"

    elif negative_score > positive_score:
        return "Negative"

    else:
        return "Neutral"


df["Sentiment"] = df["Content"].apply(
    analyze_sentiment
)

sentiment_distribution = (
    df["Sentiment"]
    .value_counts()
    .reset_index()
)

sentiment_distribution.columns = [
    "Sentiment",
    "Count"
]

print("😊 SENTIMENT ANALYSIS")
print(sentiment_distribution)

sentiment_counts = df["Sentiment"].value_counts()

plt.figure(figsize=(7, 5))

plt.bar(
    sentiment_counts.index,
    sentiment_counts.values
)

plt.title("Social Media Sentiment Distribution")
plt.xlabel("Sentiment")
plt.ylabel("Number of Posts")

plt.tight_layout()

plt.show()

top_hashtag_name = top_hashtags.iloc[0]["Hashtag"]
top_hashtag_count = top_hashtags.iloc[0]["Count"]

most_active_user = active_users.iloc[0]["User"]
most_active_user_posts = active_users.iloc[0]["Posts"]

popular_time = (
    f"{most_popular_hour:02d}:00 - "
    f"{(most_popular_hour + 1) % 24:02d}:00"
)

analytics_report = pd.DataFrame({
    "Metric": [
        "Total Posts",
        "Total Likes",
        "Total Comments",
        "Total Shares",
        "Total Engagement",
        "Average Engagement per Post",
        "Top Trending Hashtag",
        "Top Hashtag Count",
        "Most Active User",
        "Posts by Most Active User",
        "Most Popular Posting Time",
        "Positive Posts",
        "Neutral Posts",
        "Negative Posts"
    ],

    "Value": [
        len(df),
        total_likes,
        total_comments,
        total_shares,
        total_engagement,
        round(average_engagement, 2),
        top_hashtag_name,
        top_hashtag_count,
        most_active_user,
        most_active_user_posts,
        popular_time,
        sentiment_counts.get("Positive", 0),
        sentiment_counts.get("Neutral", 0),
        sentiment_counts.get("Negative", 0)
    ]
})

analytics_report

report_file = "social_media_analytics_report.csv"

analytics_report.to_csv(
    report_file,
    index=False
)

print(
    f"Report exported successfully as {report_file}"
)

files.download(report_file)