# -*- coding: utf-8 -*-
"""sales_trend_visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W6iKS6JXwoZu3t2S6Jz8A4W_2sjpTt6X
"""

import matplotlib.pyplot as plt

# Dataset
dates = ["MON", "TUE", "WED", "THU", "FRI"]
sales = [200, 250, 300, 280, 350]
highest_sale = max(sales)
lowest_sale = min(sales)

highest_day = dates[sales.index(highest_sale)]
lowest_day = dates[sales.index(lowest_sale)]
plt.figure(figsize=(8, 5))

plt.plot(
    dates,
    sales,
    marker='o',
    linewidth=3
)
plt.scatter(highest_day, highest_sale, s=120, label="Highest Sale")
plt.scatter(lowest_day, lowest_sale, s=120, label="Lowest Sale")
plt.title(" Weekly Sales Trend")
plt.xlabel("Days")
plt.ylabel("Sales")
plt.grid(True)
plt.legend()
plt.savefig("sales_trend_chart.png")
plt.show()

print("Sales trend chart generated successfully.")
print(f"Highest Sale: {highest_sale} on {highest_day}")
print(f"Lowest Sale: {lowest_sale} on {lowest_day}")