# -*- coding: utf-8 -*-
"""sales_capstone.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UaY8TKM_nwe8TT1yhX7XuO5zNxgSR-A8
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("sales_dataset.csv")

print("\nDataset Preview:\n")
print(df.head())


df.drop_duplicates(inplace=True)

df["Sales"] = pd.to_numeric(df["Sales"], errors="coerce")

df.fillna(df["Sales"].mean(), inplace=True)


total_revenue = df["Sales"].sum()

avg_sales = df["Sales"].mean()

top_product = df.groupby("Product")["Sales"].sum().idxmax()

best_region = df.groupby("Region")["Sales"].sum().idxmax()

print("\nTotal Revenue:", total_revenue)
print("Average Sales:", avg_sales)
print("Top Product:", top_product)
print("Best Region:", best_region)


sns.set_style("whitegrid")

plt.figure(figsize=(8,5))
plt.plot(df["Date"], df["Sales"], marker="o")
plt.xticks(rotation=45)
plt.title("Sales Trend")
plt.tight_layout()
plt.savefig("sales_trend.png")
plt.show()
product_sales = df.groupby("Product")["Sales"].sum()

plt.figure(figsize=(6,5))
sns.barplot(
    x=product_sales.index,
    y=product_sales.values
)
plt.title("Sales by Product")
plt.tight_layout()
plt.savefig("product_sales.png")
plt.show()

region_sales = df.groupby("Region")["Sales"].sum()

plt.figure(figsize=(6,5))
plt.pie(
    region_sales.values,
    labels=region_sales.index,
    autopct="%1.1f%%"
)
plt.title("Region-wise Sales")
plt.savefig("region_sales.png")
plt.show()

print("\n INSIGHTS")
print("1. Laptop generated the highest revenue.")
print("2. South region performed strongly.")
print("3. Sales trend shows overall growth.")
print("4. Product demand varies across regions.")
print("5. Revenue crossed ₹4 lakh in sample dataset.")