# -*- coding: utf-8 -*-
"""stock_time_series_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GfeViEo-jMKTLjpNsbMLE385H_m8Wmp6
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

data = {
    "Date": [
        "2025-08-01",
        "2025-08-02",
        "2025-08-03",
        "2025-08-04",
        "2025-08-05",
        "2025-08-06",
        "2025-08-07"
    ],
    "Stock_Price": [
        120,
        125,
        123,
        130,
        128,
        135,
        140
    ]
}
df = pd.DataFrame(data)
df["Date"] = pd.to_datetime(df["Date"])
print("\n Stock Dataset:\n")
print(df)
df["Moving_Average"] = df["Stock_Price"].rolling(window=3).mean()
print("\n Moving Average:\n")
print(df)
highest_price = df["Stock_Price"].max()
lowest_price = df["Stock_Price"].min()
peak_day = df[df["Stock_Price"] == highest_price]["Date"].values[0]
drop_day = df[df["Stock_Price"] == lowest_price]["Date"].values[0]


sns.set_style("whitegrid")
plt.figure(figsize=(5, 3))
plt.plot(
    df["Date"],
    df["Stock_Price"],
    marker='o',
    linewidth=3,
    label="Stock Price"
)

plt.title(" Stock Price Trend")
plt.xlabel("Date")
plt.ylabel("Price")
plt.xticks(rotation=45)
plt.legend()
plt.tight_layout()
plt.savefig("stock_price_trend.png")
plt.show()
plt.figure(figsize=(5,3))
plt.plot(
    df["Date"],
    df["Stock_Price"],
    marker='o',
    label="Stock Price"
)
plt.plot(
    df["Date"],
    df["Moving_Average"],
    marker='o',
    linewidth=3,
    label="Moving Average"
)
plt.title(" Moving Average Analysis")
plt.xlabel("Date")
plt.ylabel("Price")
plt.xticks(rotation=45)
plt.legend()
plt.tight_layout()
plt.savefig("moving_average_chart.png")
plt.show()
volatility = df["Stock_Price"].std()

print("\n Key Insights:")
print(f"Highest Stock Price: {highest_price}")
print(f"Lowest Stock Price: {lowest_price}")
print(f"Volatility (Std Dev): {volatility:.2f}")

print(f" Peak observed on: {peak_day}")
print(f" Lowest drop observed on: {drop_day}")