# -*- coding: utf-8 -*-
"""simple_log_analyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y-McP_e60DcOhRHmCf_wc4Y83oxbv5dm
"""

logs = [
    "ERROR DISK FULL",
    "INFO STARTED",
    "ERROR FILE MISSING",
    "WARNING MEMORY LOW",
    "INFO USER LOGIN",
    "WARNING CPU HEATING",
    "ERROR NETWORK FAILED"
]
log_count = {
    "ERROR": 0,
    "INFO": 0,
    "WARNING": 0
}

# Process logs
for log in logs:
    log_upper = log.upper()

    if "ERROR" in log_upper:
        log_count["ERROR"] += 1

    elif "INFO" in log_upper:
        log_count["INFO"] += 1

    elif "WARNING" in log_upper:
        log_count["WARNING"] += 1


print(" Log Analysis Report")
print("-" * 35)
print(f"ERROR Logs   : {log_count['ERROR']}")
print(f"INFO Logs    : {log_count['INFO']}")
print(f"WARNING Logs : {log_count['WARNING']}")
most_frequent = max(log_count, key=log_count.get)
print("\n Most Frequent Log Type:", most_frequent)
total_logs = sum(log_count.values())

print(f"\n Total Logs Analyzed: {total_logs}")